[tool.poetry]
name = "acr-ingest"
version = "0.0.0"
description = "Ingest daily ACRCloud data dumps"
authors = ["RaBe IT-Reaktion <it@rabe.ch>"]
license = "AGPLv3"
readme = "README.md"
packages = [{include = "acringest.py"}]

[tool.poetry.scripts]
acringest = 'acringest:main'

[tool.poetry.dependencies]
python = "^3.11"
cloudevents = "^1.10.1"
ConfigArgParse = "^1.7"
kafka-python = "^2.0.2"
minio = "^7.2.3"
jsondiff = "^2.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
pytest = "^8.0.0"
pytest-cov = "^4.0.0"
pytest-random-order = "^1.1.1"
pytest-ruff = "^0.2"
ruff = "^0.2.0"
isort = "^5.13.2"
pytest-isort = "^3.1.0"

[tool.ruff]
[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "E", "I", "PL", "UP", "RUF100"]
fixable = ["ALL"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "7.2"
addopts = "-ra -q --random-order --doctest-glob='*.md' --doctest-modules --cov=acringest --cov-fail-under=100 --ruff --isort --ignore docs/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
