[lint]
select = ["ALL"]
ignore = [
	"D203",
	"D213",
]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "D", "ANN", "INP001", "DTZ001", "S108"]
"**/__init__.py" = ["D104"]
"docs/gen_ref_pages.py" = ["INP001"]
