name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.22.1
    with:
      image: ghcr.io/radiorabe/acringest
      name: acringest
      display-name: Ingest daily ACRCloud data dumps
      tags: minimal rhel9 ubi9 rabe minio kafka cloudevents acrcloud
      cosign-base-image-only: false
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.22.1
