name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-python-poetry:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@v0.34.1
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@v0.34.1
